name: Regenerate SDKs

on:
  push:
    paths:
      - "example/example.yml"

jobs:
  generate-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trigger SDK Generation
        uses: the-codegen-project/github-action@v0.2.1
        with:
          spec_id: 4aa2cde8-3976-4b0a-b9b8-4fef6d440e0e
          api_token: ${{ secrets.CODEFORGE_API_TOKEN }}
          api_url: 'https://juicily-abstemious-sherilyn.ngrok-free.dev'
